Event model branch
iiitv/club_calender pull request #23
Opened 2020-09-02 11:30 UTC by vikiwarrior

issue #10

2020-09-03 03:46 UTC, thecodepapaya requested changes
Use proper indentation. You can use the formatter which comes bundled with Flutter plugin in your IDE.

2020-09-03 04:19 UTC, vikiwarrior commented
Sure ,I will keep that in mind

2020-09-03 05:03 UTC, thecodepapaya commented
PTAL at the updated [Model Wiki](https://github.com/iiitv/club_calender/wiki/Models). I have specified the data types for the attributes.

2020-09-04 10:06 UTC, thecodepapaya approved these changes

2020-09-04 10:06 UTC, merged